### ISSUE TITLE
Disable/Remove the dropdown with "Examples" on the right

### ISSUE THREAD

**Issue by uxRoy19** [genai-apps/aggrag#50] opened 2024-08-08 08:33 UTC
if someone selects an examples from the one on the right side then following is the output, which is a blocker and would lead for the user to be confused facing this affecting the UX as well. (refer the link below)
https://drive.google.com/file/d/1em1IEEkp23y8dmZtMlqchPJFBg2sovJt/view?usp=sharing

@tarun-goyal

**Comment by garvk** [comment] 2024-09-19 14:26
@tarun-goyal  @uxRoy19 @santhosh-kumar12532 

[merge request 101](https://github.com/genai-apps/aggrag/pull/101) captures the changes suggested in this ticket, however, it only removes the examples but the dropdown still exists in the top right corner (refer screenshot). 

Since we have not added other examples besides our 1 case study, I feel the 'examples' should be left there as is because they act as a good learning point for a new user. I agree, leaving them there might cause some ux confusion, maybe it's a small cost to pay at this point. 
 

<img width="300" alt="Screenshot 2024-09-19 at 7 53 07 PM" src="https://github.com/user-attachments/assets/c2613816-f908-419c-a447-71b44d2c1b50">

**Comment by tarun-goyal** [comment] 2024-09-19 16:05
@garvk The problem is none of the Examples is working right now, as we are getting this error:
![image](https://github.com/user-attachments/assets/c23272ce-be4d-40d0-9a26-f7e0a5c03862)

So if we want to keep showing a few other examples, we need to fix this first. Depending on the effort needed on this, we can decide if we want to fix it now OR disable "Examples" CTA until then.

**Comment by garvk** [comment] 2024-09-24 12:30
@tarun-goyal The error you shared is fixed on both the local and deployed version. 

'OpenAI Evals' is not working under examples so will update the pull request accordingly.

> @garvk The problem is none of the Examples is working right now, as we are getting this error: ![image](https://private-user-images.githubusercontent.com/16475306/369078504-c23272ce-be4d-40d0-9a26-f7e0a5c03862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODExMDcsIm5iZiI6MTcyNzE4MDgwNywicGF0aCI6Ii8xNjQ3NTMwNi8zNjkwNzg1MDQtYzIzMjcyY2UtYmU0ZC00MGQwLTlhMjYtZjdlMGE1YzAzODYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDEyMjY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNDg3ZmU5NTI5OGFiOTFmZDRhODMyZjIwYTI1OWRmY2RmOWNjZDdkNWQ0Njg1ODA3OGE3NjYwNTg3YWFkNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ICGSxqx1kFDwasDWJyZobhCUGwe_1uDwR8b6OHIWyHk)
> 
> So if we want to keep showing a few other examples, we need to fix this first. Depending on the effort needed on this, we can decide if we want to fix it now OR disable "Examples" CTA until then.

**Closed** 2024-10-20 09:46 UTC
Labels: bug, enhancement
